version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: lyss-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=lyss
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=lyss_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: lyss-redis
    ports:
      - "6380:6379"
    command: redis-server --requirepass lyss_redis_password
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
